### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by Meet1103** [Dhaval1403/master-the-event-loop#1]
It is important to understand how the event loop system and the different parts are working together.
This task has to be done by all team members!!!

- [x] Callstack

- [x] Web API

- [x] Job Queue 

- [x] Callback Queue

- [x] Datastructure Queue

**Comment by r4pt0s** [comment]
@Avelansh
@AkinAguda
@gideonlexy
@anaol
@tubacatal
@brainy099
@faizhameed

I think this task is finished.
Is everybody now a master regarding to this topic?
