### ISSUE TITLE
Website Container Component

### ISSUE THREAD

**Issue by Meet1103** [Dhaval1403/master-the-event-loop#3]
This component should contain all other components and is basically the container. It should look close like this 

<img width="846" alt="Screenshot_2020-01-21_at_14 03 18-1" src="https://user-images.githubusercontent.com/29685827/73933351-8fc0be80-48dc-11ea-9e92-90e7ef416f54.png">

**Comment by anaol** [comment]
I want this one.

**Comment by Meet1103** [comment]
Done !!
