### ISSUE TITLE
Code Editor Component

### ISSUE THREAD

**Issue by Meet1103** [Dhaval1403/master-the-event-loop#4]
The Code editor component is the most challenging one.
In the first iteration, it should only act like a code editor. 
At a later point in time, it should visually show a border around each line of code which gets actually sent to the callstack.

**Comment by r4pt0s** [comment]
As reference 
[Code Playground Stephen Grider](https://github.com/StephenGrider/playgrounds)

**Comment by AkinAguda** [comment]
I'd like to do this one please!

**Comment by r4pt0s** [comment]
Congratulations. You have chosen one of the most challenging components.
If you need more informations about anything, just ask on here or on Discord.
