### ISSUE TITLE
Callstack Component

### ISSUE THREAD

**Issue by Meet1103** [Dhaval1403/master-the-event-loop#5]
The Callstack component has to receive a input from the codeeditor if the user hits "play". It then has to decide what it should do with this snippet. Is there anything else or is it a simple statement.
If the line of code is part of the web api, it should send it to this component.
If the line of code is simple like a console.log, it should pop it off of the stack and push it to the console because this component has to generate an output there.

It is coupled to the event loop component because this component has to check if it is empty or not.

**Comment by gideonlexy** [comment]
I want to work on this

**Comment by Meet1103** [comment]
Done !!

**Comment by Dhaval1403** [comment]
The callstack component is been created.
