### ISSUE TITLE
Web Api Component

### ISSUE THREAD

**Issue by Meet1103** [Dhaval1403/master-the-event-loop#6]
The Web API component receives a input from the callstack component which it should display.

**Comment by Avelansh** [comment]
assign this issue to me...

**Comment by Meet1103** [comment]
Done !!

**Comment by r4pt0s** [comment]
@Avelansh 
Please change the directory structure. We follow this pattern
```
components/
    name-of-compenent/
        Component.js
```

**Comment by Dhaval1403** [comment]
The webapi component is been created.
